syntax enable
let g:solarized_termcolors=256
set number
set spell spelllang=en_us
filetype indent plugin on
set wildmenu
set hlsearch
set autoindent
set mouse=a
set ruler
set so=4
set showmatch
set background=light
colorscheme solarized
